/// @description Insert description here
draw_set_color(c_black);
//draw_text_transformed(room_width/2-100,room_height/2-50,"GAME OVER",4,3,0);

draw_text_transformed(425,200,"GAME OVER! YOU WIN!",4,3,0);
draw_text(425,300,"Credits: ");
draw_text(425,320,"Programming: Vasiliy Ulin ");
draw_text(425,350,"Graphics: Vasiliy Ulin");
draw_text(425,380,"Audio: Generated by Vasiliy Ulin using online sound generation tools: ");
draw_text(425,400,"sfxr, freesoundeffects.com,Wolfram Tones,http://soundbible.com");
draw_text(425,430,"Game idea: Was helped by a friend of mine, Trevor Roark."); 
draw_text(425,460,"Thanks bud for discussing different game ideas with me");
draw_text_transformed(125,600,"THANKS FOR PLAYING! HOPE YOU ENJOYED!",3,2,0);
draw_text_transformed(125,650,"Press ESC to exit / close the game or 'R' to restart",2,2,0);




